### ISSUE TITLE
Icon flickering when positioned deferent than default

### ISSUE THREAD

**Issue by juraj-hrivnak** [ZZZank/MiniEffects-ExtendedLife#1]
The potion icon flickers when hovered on with the mouse.
Note that this only happens when the icon is positioned differently than the default.

I also have HEI and Reskillable installed. I don't know if it's related.

**Comment by ZZZank** [comment]
will this happen when offsets are relatively small or only happens when x/y offsets are quite large?

**Comment by juraj-hrivnak** [comment]
Yes, I set the y offset to 64.

**Comment by juraj-hrivnak** [comment]
https://github.com/user-attachments/assets/19401352-016c-4ac5-b6ca-0ff12ec45f77

**Comment by ZZZank** [comment]
2.0.1 will be avaliable on CurseForge soon

https://github.com/user-attachments/assets/b86f9b5b-b3d0-496e-a10d-1ec94884410a

**Comment by juraj-hrivnak** [comment]
Nice, thank you very much!
