### ISSUE TITLE
Reskillable compatibility 

### ISSUE THREAD

**Issue by juraj-hrivnak** [ZZZank/MiniEffects-ExtendedLife#2]
When Reskillable is installed, the extended potion effects clash with the JEI bookmarks because the Reskillable skill tabs shifted them.

![2024-09-09_16 56 12](https://github.com/user-attachments/assets/f50bc2f5-ab91-4275-84b8-98d3395ba181)

**Comment by ZZZank** [comment]
2.1.0 has been released, fixing this issue:
(ignore those blue rectangles, they are for debug)

https://github.com/user-attachments/assets/6ed687f4-8655-447c-8e23-e9710c70b988

link: https://www.curseforge.com/minecraft/mc-mods/minieffects-legacy-extended-life/files/5716574

the time took for fixing is a bit longer than expected, and sorry for lack of response to this issue, I'm not in a good state recently

**Comment by juraj-hrivnak** [comment]
Thank you for the update! No worries, your response was quicker than from most modders, and you do this for free.
I wish you all the best, teksturepako
